services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: domsphere-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: domsphere
      POSTGRES_USER: domsphere
      POSTGRES_PASSWORD: domsphere
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U domsphere -d domsphere"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
    driver: local
